[package]
name = "gladsheim"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.38", features = ["derive"]}
geo-types = "0.7.16"
osmpbf = "0.3.5"
polyline = "0.11.0"
thiserror = "2.0.12"
